---
name: CI

on:
  push:
    branches:
    - kirin

jobs:
  deploy:
    name: deploy to gh-pages
    runs-on: ubuntu-22.04

    steps:
    - name: checkout source repo
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        path: source

    - name: copy meta files for pnpm/cache
      run: |
        cp source/package.json .
        cp source/pnpm-lock.yaml .

    - name: install pnpm lol
      uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd # v2.2.1

    - name: install node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # 3.4.1
      with:
        node-version: 18.7.0
        cache: pnpm

    - name: install dependencies
      working-directory: source
      run: pnpm i

    - name: build
      working-directory: source
      run: pnpm run build

    - name: checkout gh-pages branch
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        path: gh-pages
        ref: gh-pages

    - name: install fish
      run: |
        sudo add-apt-repository -yn ppa:fish-shell/release-3
        sudo apt-get update
        sudo apt-get install fish

    - name: publish
      shell: fish {0}
      run: |
        # clean
        rm -rf gh-pages/*
        mv gh-pages/.git gh-pages/git
        rm -rf gh-pages/.*
        mv gh-pages/git gh-pages/.git

        # copy output into gh-pages branch
        cp source/.output/public/404/index.html source/.output/public/404.html
        cp -R source/.output/public/* gh-pages
        cp -R source/.output/public/.* gh-pages

        cd source

        set COMMIT_MESSAGE "automated deploy from commit "(git rev-parse HEAD)

        cd ../gh-pages

        git config --global user.name smol
        git config --global user.email "107521333+a-tiny-kirin@users.noreply.github.com"
        echo https://a-tiny-kirin:${{ secrets.GITHUB_TOKEN }}@github.com > .git/credentials
        git config --global credential.helper "store --file=.git/credentials"
        git config --unset-all http.https://github.com/.extraheader # https://stackoverflow.com/a/69979203

        git add -A
        git commit -m "$COMMIT_MESSAGE"
        git push
